# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.2.dev5+ge21ca9d.d20230130'
__version_tuple__ = version_tuple = (0, 0, 2, 'dev5', 'ge21ca9d.d20230130')
